<a href="https://colab.research.google.com/github/yaseen2402/deep-learning/blob/main/pytorch_begins.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [ ]:
scalar.item() #get tensor back as python int

9

In [ ]:
scalar.ndim

0

In [ ]:
torch.empty(2, 3) #create and empty tensor: allocates memory

tensor([[-3.8825e-18,  4.4507e-41,  5.4921e+00],
        [ 0.0000e+00, -8.1797e-25,  4.4505e-41]])

In [ ]:
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[12, 14, 15], [23, 34, 45], [56, 67, 78]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

##Random Tensors

In [ ]:
random_tensor = torch.rand(2, 3, 4)
random_tensor #these values will be different everytime, use seed if u want same value

tensor([[[0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854, 0.5739]],

        [[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]])

In [ ]:
torch.manual_seed(42)
r = torch.rand(2, 3)
r

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
zeros = torch.zeros(3, 4) #can be used for masking
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(1, 11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
ten_zeros = torch.zeros_like(one_to_ten) #creates tensor with same shape as the one specified in parameter 'input'
ten_zeros

tensor([0, 0, 0, 0, 0])

In [ ]:
empty = torch.empty_like(ten_zeros)
empty

tensor([     1087061968, 136415183584480,              64,              96,
             1085235763])

In [ ]:
empty.dtype

torch.int64

In [ ]:
torch.rand_like(empty) #empty has integer values but rand produces float so this throws error

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
torch.rand_like(empty, dtype = torch.float32)

tensor([0.5936, 0.8694, 0.5677, 0.7411, 0.4294])

In [ ]:
if torch.cuda.is_available():
  print("cuda gpu available:", torch.cuda.get_device_name(0))

else:
  print("no gpu available")



no gpu available


In [ ]:
torch.eye(4) #identity matrix

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
x = torch.full((3, 2), 99) # specify the shape and what value it should hold
x

tensor([[99, 99],
        [99, 99],
        [99, 99]])

In [ ]:
x = x/2
x

tensor([[49.5000, 49.5000],
        [49.5000, 49.5000],
        [49.5000, 49.5000]])

In [ ]:
x+3

tensor([[52.5000, 52.5000],
        [52.5000, 52.5000],
        [52.5000, 52.5000]])

In [ ]:
a = torch.full((2, 3), 40)
b = torch.full((2, 3), 10)
a, b

(tensor([[40, 40, 40],
         [40, 40, 40]]),
 tensor([[10, 10, 10],
         [10, 10, 10]]))

In [ ]:
a+b

tensor([[50, 50, 50],
        [50, 50, 50]])

In [ ]:
a-b

tensor([[30, 30, 30],
        [30, 30, 30]])

In [ ]:
a*b

tensor([[400, 400, 400],
        [400, 400, 400]])

In [ ]:
a/b

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [ ]:
a**b #power

tensor([[10485760000000000, 10485760000000000, 10485760000000000],
        [10485760000000000, 10485760000000000, 10485760000000000]])

In [ ]:
y = torch.tensor([-1, -2.5, 3, 5])

In [ ]:
torch.abs(y)

tensor([1.0000, 2.5000, 3.0000, 5.0000])

In [ ]:
torch.neg(y)

tensor([ 1.0000,  2.5000, -3.0000, -5.0000])

In [ ]:
torch.round(y)

tensor([-1., -2.,  3.,  5.])

In [ ]:
torch.sum(y)

tensor(4.5000)